### PR TITLE
Add support for Futo Android keyboard

### PR DESCRIPTION
**Pull request by QADavidCalvo**
Add support for Futo Android keyboard

🔍️ Description

Added Futo to the available Android keyboards and the Xpaths needed to map the keys and suggestions.

🧐 Context

Only for Android devices (emulators and real devices)

⚠️ Side-effects / Shortcomings

none

✅ How this was tested ?

To map the keys run `kebbie show_layout -K futo`
To evaluate the keyboard run `kebbie evaluate -K futo`

## 🌱 Checklist

- [ ] Perform self-review of my own code
- [ ] Comment the code, particularly in hard-to-understand areas
- [ ] Update the documentation accordingly to the new code
- [ ] Lint / format the code
- [ ] Update existing tests / Add new tests
- [ ] Tests are passing locally

### CODE REVIEW

**Comment by QADavidCalvo** [comment]
Seems that the tests are not passing @astariul 
I've launched them locally and they worked...

**Comment by astariul** [comment]
Tests are passing, it's just the coverage badge is not up-to-date.

You can update it locally with : 

```
pytest
coverage-badge -o .github/badges/coverage.svg -f
```

And then push the changes.

---

Let's find a better way to deal with this coverage badge...

**Comment by astariul** [comment]
Looking good ! Thanks for re-organizing the dictionary 😅 

We just have to update the documentation and we are good to go 👍

**Comment by QADavidCalvo** [comment]
I did it but no files were changed...
Done again and badge updated correctly.

**Pull request closed without merging**
