### PR TITLE
 Add support for Yandex Android keyboard

### PR DESCRIPTION
**Pull request by QADavidCalvo**
Add support for Yandex Android keyboard 

## 🔍️ Description

Added yandex to the available Android keyboards and the Xpaths needed to map the keys and suggestions.

## 🧐 Context

Only for Android devices (emulators and real devices)

## ⚠️ Side-effects / Shortcomings

The numbers layout is not mapped

## ✅ How this was tested ?

To map the keys run `kebbie show_layout -K yandex`
To evaluate the keyboard run `kebbie evaluate -K yandex`

## 🌱 Checklist

- [ ] Perform self-review of my own code
- [ ] Comment the code, particularly in hard-to-understand areas
- [X] Update the documentation accordingly to the new code
- [ ] Lint / format the code
- [ ] Update existing tests / Add new tests
- [X] Tests are passing locally

### CODE REVIEW

**Comment by astariul** [comment]
So, usually, the number layout is not mapped when we can't find the button "numbers".
This happens because the code expect to have a button called "numbers", so that we can click it and access the number layout.

This is because this kind of button (alongside other magic buttons like shift, enter, backspace, etc...) have a different name in each keyboard.

To debug this, I usually print the XML right before the code crashes. So for example, add a `print(self.driver.page_source)` between here : 
https://github.com/FleksySDK/kebbie/blob/a4e2074d5200fb33999ed09ee09ee54539a2ce7c/kebbie/emulator.py#L759-L766

In the XML, you can see the list of keys, and you can find the one for the magic keys : 

```
[...]
<ya.d index="20" class="ya.d" text="z" content-desc="z" bounds="[162,1986][271,2130]" displayed="true" />
<ya.d index="21" class="ya.d" text="x" content-desc="x" bounds="[270,1986][379,2130]" displayed="true" />
<ya.d index="22" class="ya.d" text="c" content-desc="c" bounds="[378,1986][487,2130]" displayed="true" />
<ya.d index="23" class="ya.d" text="v" content-desc="v" bounds="[486,1986][595,2130]" displayed="true" />
<ya.d index="24"class="ya.d" text="b" content-desc="b" bounds="[594,1986][703,2130]" displayed="true" />
<ya.d index="25" class="ya.d" text="n" content-desc="n" bounds="[702,1986][811,2130]" displayed="true" />
<ya.d index="26" class="ya.d" text="m" content-desc="m" bounds="[810,1986][919,2130]" displayed="true" />
<ya.d index="27" class="ya.d" text="" content-desc="Delete." bounds="[918,1986][1080,2130]" displayed="true" />
<ya.d index="28" class="ya.d" text="" content-desc="To symbols." bounds="[0,2130][141,2219]" displayed="true" />
<ya.d index="29" class="ya.d" text="" content-desc="Switch language." bounds="[140,2130][260,2219]" displayed="true" />
[...]
```

So here for example, `Delete.` is the backspace, and `To symbols.` is the numbers key.

Once you found the name of these magic keys, you can update `CONTENT_TO_IGNORE` and `CONTENT_TO_RENAME` accordingly : 

* `CONTENT_TO_IGNORE` is a list of keys that should be ignored
* `CONTENT_TO_RENAME` is a dictionary where we rename the given key into the given value

So in this case, you would add to `CONTENT_TO_RENAME` : 
```
"Delete.": "backspace",
"To symbols.": "numbers",
```

etc...

Once the naming are properly mapped, the numbers layout should be properly detected.

---

Note that once the number layout is properly detected, you might encounter the same error on the next layout... You need to do the same !

And then, once the layout is properly detected, you need to adapt the code for retrieving the predictions properly 👍 

---

I'll let you try to do it by yourself, if you have some difficulties let me know, I'll take a closer look.

**Comment by QADavidCalvo** [comment]
Numbers layout fixed.
Captura de pantalla 2024-05-23 a las 11 31 49

But the keys are shifted up.

**Comment by astariul** [comment]
@QADavidCalvo Can you push your changes to the remote ? It seems the PR wasn't updated so I can't see your changes

**Comment by astariul** [comment]
Screenshot 2024-05-24 at 10 50 11 AM

It seems shifted on my emulator too...

**Comment by astariul** [comment]
Ah I got it, it's because you didn't pull the latest changes from `main`. I think you created your branch before #26 was merged.

If you just pull the latest changes from `main` and merge to your branch, it should fix the issue : 

```
git checkout main
git pull
git checkout android-yandex-keyboard-support
git merge --no-ff main
```

**Comment by astariul** [comment]
(ah and I think the code for retrieving the predictions is wrong ? Is it working for you locally ?)

**Comment by QADavidCalvo** [comment]
With the last changes (merged from main), the keys are correctly mapped:
Captura de pantalla 2024-05-24 a las 10 04 24

**Review by astariul — APPROVED** [review]
LGTM !

**Pull request merged**
